Gray-Space/src/objects/GS_Club__c.object
<CustomObject>
    <fields>
        <fullName>GS_Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Gray-Space/src/objects/GS_Club_Member__c.object
<CustomObject>
    <fields>
        <fullName>GS_Club__c</fullName>
        <label>Club</label>
        <referenceTo>GS_Club__c</referenceTo>
        <relationshipLabel>Club Members</relationshipLabel>
        <relationshipName>Club_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GS_Interest_In__c</fullName>
        <label>Interest In</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GS_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Club Members</relationshipLabel>
        <relationshipName>Club_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Club Member</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Club Memeber Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Gray-Space/src/objects/GS_General__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>GS_GrayFamily_Id__c</fullName>
        <label>GrayFamily Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>General</label>
</CustomObject>

Gray-Space/src/classes/GS_GrayFamilyJoinIn.cls
public with sharing class GS_GrayFamilyJoinIn {

    @AuraEnabled(cacheable=true)
    public static String getDescription() {
        GS_Club__c club = getClub();

        return club.GS_Description__c;
    }

    @AuraEnabled
    public static void addMember(String interestIn) {
        GS_Club__c club = getClub();
        User loggedUser = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        GS_Club_Member__c member = new GS_Club_Member__c(GS_Member__c=loggedUser.ContactId, GS_Club__c=club.Id, GS_Interest_In__c=interestIn);

        insert member;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean isClubMember() {
        GS_Club__c club = getClub();
        User loggedUser = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        List<GS_Club_Member__c> members = [SELECT Id FROM GS_Club_Member__c WHERE GS_Club__c=:club.Id AND GS_Member__c=:loggedUser.ContactId];
        return members.size() > 0;
    }

    @AuraEnabled(cacheable=true)
    public static GS_Club__c getClub() {
        GS_General__c settings = GS_General__c.getOrgDefaults();
        return [SELECT Id, GS_Description__c FROM GS_Club__c WHERE Id = :settings.GS_GrayFamily_Id__c];
    }
}